### ISSUE TITLE
Fix Broken P_3_1_2_02

### ISSUE THREAD

**Issue by b-g** [generative-design/Code-Package-p5.js#111]

**Comment by b-g** [comment]
See repaired P_3_1_2_01

**Comment by Niels-NTG** [comment]
So… this issue is resolved then? https://github.com/generative-design/Code-Package-p5.js/commit/367bbb150e6edf8904a6395c865b30b7b7cc6cac

**Comment by b-g** [comment]
No, P_3_1_2_01 is working and is P_3_1_2_02 partly broken.
