### ISSUE TITLE
P_2_1_1_04 does not load (SVGs in Firefox)

### ISSUE THREAD

**Issue by joeyklee** [generative-design/Code-Package-p5.js#123]
It seems maybe to be an issue with loadImage() and svg. I get the following error:

```
InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable  p5.js:14640
	[49]</p5.Renderer2D.prototype.image http://localhost:8000/libraries/p5/p5.js:14640:5
	[61]</p5.prototype.image http://localhost:8000/libraries/p5/p5.js:20795:3
	bound  self-hosted:918:17
	setup http://localhost:8000/01_P/P_2_1_1_04/:62:3
	p5/this._setup< http://localhost:8000/libraries/p5/p5.js:11564:7
	bound  self-hosted:912:17
	p5/this._runIfPreloadsAreDone http://localhost:8000/libraries/p5/p5.js:11507:7
	p5/this._decrementPreload http://localhost:8000/libraries/p5/p5.js:11516:5
	bound  self-hosted:914:17
	[61]</p5.prototype.loadImage/img.onload
```

While something seems to get loaded when testing the loadImage() with a callback, if you try to console.log() any of the images in the `shapes` array, it doesn't return anything in Firefox. 

Things seem to work in Chrome.

**Comment by b-g** [comment]
@joeyklee Thanks for reporting this ... I upgraded everything to p5.js v0.5.11. Hopefully this resolves it, if not submit an issue at https://github.com/processing/p5.js/issues

**Comment by Niels-NTG** [comment]
Nope, updating to p5 v0.5.11 didn't help.

**Comment by joeyklee** [comment]
Hi! I converted the SVGs to PNGs and loaded each image and seems to be working... should we use this as a temporary solution? if so, I will make a PR. :

```
function preload() {
  shape1 = loadImage("data/module_1.png");
  shape2 = loadImage("data/module_2.png");
  shape3 = loadImage("data/module_3.png");
  shape4 = loadImage("data/module_4.png");
  shape5 = loadImage("data/module_5.png");
  shape6 = loadImage("data/module_6.png");
  shape7 = loadImage("data/module_7.png");
}
```

**Comment by b-g** [comment]
Hi + thanks! Before we finally go down the png route ... did you try `0.5.14` too?

**Comment by b-g** [comment]
+ Did you report the issue to the p5.js peeps? (They just can fix things if they know the bugs)

**Comment by joeyklee** [comment]
So looks like the `loadImage()` works on `.svg` in 0.5.14 in Chrome and Safari, but Firefox returns the same error above. I will report to the p5.js and see if we can get some love :)

**Comment by joeyklee** [comment]
Just submitted the issue here: https://github.com/processing/p5.js/issues/2150

**Comment by b-g** [comment]
Great! Let's wait what comes back ...

**Comment by joeyklee** [comment]
@b-g - please see the explanation here: https://github.com/processing/p5.js/issues/2150

As explained:
```
Basically it's a bug in Firefox that cause it to not draw SVG images onto canvas if the SVG themselves does not have a non-percentage width and height attribute. Simply adding on the width and height attribute onto the root <svg> tag will solve this.
```

How should we proceed? Should we add the width/height attribute to each of the svg files?

**Comment by b-g** [comment]
@joeyklee Thanks for investigation this! Can you add the corresponding width/height attribute into the (or better all) svg files? Would be great to have Firefox working out of the box with SVG loading sketches.

**Comment by joeyklee** [comment]
@b-g - sure thing. will take of this now and make  PR. Stay tuned.
