### ISSUE TITLE
Synchronize and check P_1_2_3_02 to _05

### ISSUE THREAD

**Issue by bohnacker** [generative-design/Code-Package-p5.js#130]
P_1_2_3_02 to _05 needs to be synchronized with P_1_2_3_01:
- Variable names as much as possible
- Key interaction
- Code cleaning

**Comment by Niels-NTG** [comment]
Done. https://github.com/generative-design/Code-Package-p5.js/commit/831c25cd5720947767a12cd678b1cf36db3b2c1c
