### ISSUE TITLE
P_3_1_4_01: put Treemap class into the gd-library

### ISSUE THREAD

**Issue by bohnacker** [generative-design/Code-Package-p5.js#150]
I'm wondering if the class should be more general in terms of data input. But then it might be changing something in the printed code...

**Comment by bohnacker** [comment]
Before putting it to the Library, the Treemap class has to be cleaned up. I will do that, and reopen the issue after that.

**Comment by bohnacker** [comment]
The Treemap class is now somehow solid and could be put to the library.

**Comment by b-g** [comment]
@bohnacker Done! Please note `new gd.Treemap()` e.g. https://github.com/generative-design/Code-Package-p5.js/blob/master/01_P/P_3_1_4_01/sketch.js#L56
