### ISSUE TITLE
Readme: Add Acknowledgments and Contributors Link 

### ISSUE THREAD

**Issue by b-g** [generative-design/Code-Package-p5.js#155]

**Comment by joeyklee** [comment]
let me know if I can help with this :)

**Comment by b-g** [comment]
Thanks! will do a first iteration ... would then be great having you go over it. But low prio at them moment, a very last thing.

**Comment by joeyklee** [comment]
@b-g alrighty, I'll go through it when the time comes. Thanks!

**Comment by joeyklee** [comment]
Hi @b-g - should I submit through pull request? It seems I don't have the access rights to write to the repository anymore.

**Comment by b-g** [comment]
Hi @joeyklee Sorry! Should be good now. Gave you write access to the repo via adding you to the team "Authors". Please commit directly into the pre-release branch. Best, B

**Comment by b-g** [comment]
Good for me know. Thanks everyone! Will close the issue.
