### ISSUE TITLE
Cross check data/README.md

### ISSUE THREAD

**Issue by b-g** [generative-design/Code-Package-p5.js#163]
Hi @joeyklee 

Reorganised the centralised /data folder and introduced a dedicated readme. Could you please cross check whether understandable/spelling?

https://github.com/generative-design/Code-Package-p5.js/blob/pre-release/data/README.md

cc @Niels-NTG

**Comment by joeyklee** [comment]
I'll check it out today and will edit/close issue when appropriate. thanks!

**Comment by joeyklee** [comment]
Should be clear now with https://github.com/generative-design/Code-Package-p5.js/commit/2772d5d368f5d3640082ee56e54b23d8f751720f
