### ISSUE TITLE
Code-Package-p5.js for p5js-web-editor 

### ISSUE THREAD

**Issue by joeyklee** [generative-design/Code-Package-p5.js#165]
@b-g 
Regarding getting the sketches into the p5-web-editor, the idea is to pull the sketches from github. However, this means we would need to put the "encapsulated" sketches somewhere on github. Problem is that when the sketches contain the GG library, etc for each sketch the projects is an unweildy ~610mb (~550 excluding the node_modules). 

Question is, should we put the encapsulated code package in the generative-design org or in a separate dummy account? 

thanks!

**Comment by joeyklee** [comment]
Also will follow up via email regarding what the web editor username/password/email should be.

**Comment by Niels-NTG** [comment]
A few months ago I was looking into getting rid off jQuery. That will save some space. And I don't think all the packages listed in `package.json` are required for running the a sketch. Some of them are only required for setting up locally. These could be moved to `devDependencies` in `package.json`.

**Comment by joeyklee** [comment]
@Niels-NTG true, but still each sketch is about 2mb with all the required libs included

**Comment by joeyklee** [comment]
Just had a chat with Cassie - she suggested serving our libs via https://rawgit.com/ but it is not really meant for production. any plans for a cdn by chance  for the libs @b-g ?

**Comment by joeyklee** [comment]
also current most feasible plan seems to be to offload as much of the external references to CDN (e.g. jquery, tooltipster, chromajs, opentype.js, etc) and then we can either serve up our stuff via some other channel (e.g. rawgit) or include our libs in the editor proj folder but that's less optimal. It seems that ideally less files in the p5 editor the better.

**Comment by joeyklee** [comment]
ah! actually looks like rawgit has urls for production code!

**Comment by b-g** [comment]
@joeyklee Many thanks for looking into it!

Basically I would prio everything like this:

1. solution should be ready by mit/end of Feb
2. keep in mind maintainability. There will be bugs ... there has to be a way to quickly update and deploy to the p5 online editor
3. keep in mind the long term support. We will have to maintain this baby for 10 years!!

Keep me in the loop, but don't wait on me. Simply go ahead, you are much closer to the p5 community/devs.

(Yes serving more files via a CDN sound more elegant. We could simply create a single index.html which includes everything for the p5 online editor sketches. Keep in mid the [central /data folder](https://github.com/generative-design/Code-Package-p5.js/tree/pre-release/data). There might be CDN source for tweemoji anyway already etc.)

**Comment by joeyklee** [comment]
@b-g - cool. I will need 1 or 2 days to work it out. Should be ready by the end of next week, but of course I will aim for earlier. Thanks!

**Comment by joeyklee** [comment]
Just did a little poking around. @Niels-NTG can you confirm that the follow libraries aren't actively being used?

```
filesaver
kd-tree
quantize
treemap-squarify
```

i'm planning to bundle up the libs that don't have a cdn and would be good to know which ones we can leave out. 

thanks!

**Comment by joeyklee** [comment]
Also for the P5-web-editor I will leave out the `tooltipster` libs

**Comment by Niels-NTG** [comment]
@joeyklee 

- `FileSaver` is used for saving animated GIFs of sketches `P_2_3_7_01` and P_2_3_7_02_TABLET`.
- `kd-tree` is used in the emoji sketches `P_4_3_4_01` and `P_4_3_4_02` for sampling the correct colours.
- `quantize` is only used in A_Cover_Image_Colors. This one is optional IMO.
- `treemap-squarify` doesn't seem to be used anywhere anymore and could be removed.

**Comment by joeyklee** [comment]
Ah! thanks for catching that @Niels-NTG - ok I will take care to include them in the bundled.js file for the web editor. Thank you!

**Comment by joeyklee** [comment]
@Niels-NTG maybe I misunderstood what Browserify is doing, but my understanding is that I could roll up all of the dependencies into a `bundled.js` file and then include that within a set of`<script></script>` and then have access to the lib contents... is that not the case?

**Comment by joeyklee** [comment]
<img width="1167" alt="screen shot 2018-01-27 at 13 23 24" src="https://user-images.githubusercontent.com/3622055/35475023-479f1dc2-0365-11e8-8bbb-bafb1e4ad1ff.png">
the generative-design library loads it seems but then the `gd` object doesn't seem to be available globally :/

**Comment by b-g** [comment]
@joeyklee Yes my understanding of what Browserify is doing is quite different ... I think we need a different approach. 

I would suggest to simply concat all the existing js files which we need into a singe one. Simply coping the contents of the files in to a single file without touching and messing around with the content. e.g. `npm run concat` could be:

```
concat -o bundled.js ./node_modules/g.js/dist/g.min.js ./otherfile.js ./otherfile.js ./otherfile.js
// I would also use the min versions of the libs if available
// https://www.npmjs.com/package/concat
```
Please keep in mind individual dependencies of sketches like P_4_3_4_02 and emoji-average-colors.js = a small file with some data only relevant for the emoji sketches ... which is not suited for the bundling.

**Comment by joeyklee** [comment]
thanks @b-g! yeah I discovered this after far too long. 
the plan is to concat then all the js libs into a nice little bundle and then for the special sketches with an additional js file just to download that into the p5-editor programatically with the upload script.

I'm chipping away at it. Gotta take care of course stuff for monday, then I'll be back on it Tuesday, onwards.

**Comment by joeyklee** [comment]
Hi All - updates on the p5-editor front.

I've got a first version working: https://github.com/joeyklee/p5.js-web-editor/blob/master/server/examples-gg-latest.js

It took a fair amount of refactoring and getting acquainted with promises in all their forms and more.  Fun exercise, but still some todos to take care of.

1. [ ] Can we link the fonts somehow or is it possible to just drop this for the p5 editor? /Users/joeyklee/Code/src/github/generative-design/Code-Package-p5.js/01_P/P_3_2_2_01/data/FreeSans.otf
2. [ ] the video in `P_4_2_2_01` exceeds the mongdb file size limits. Either we exclude this sketch or find a way to shorten the video. currently the video files there are > 18mb. 
3. [ ] need to test all the sketches and remark which ones aren't working for whatever reason ==> if you want to test. I can send you the `credentials` to setup in the `.env` so you can also run them locally. 

more news tomorrow :)

**Comment by joeyklee** [comment]
## Font files not well suited for p5editor as they are stored in mongodb ==> weird binary stuffs!
<img width="1528" alt="screen shot 2018-02-01 at 23 50 56" src="https://user-images.githubusercontent.com/3622055/35717537-cce6e34c-07ad-11e8-9d91-ab208fa7fd56.png">

## but there's hope as the simple sketches are working
<img width="1528" alt="screen shot 2018-02-01 at 23 51 12" src="https://user-images.githubusercontent.com/3622055/35717544-e2e223c8-07ad-11e8-831c-a99f9473548f.png">

**Comment by b-g** [comment]
@joeyklee Great + Yay!

1. Could you not directly link to e.g. https://github.com/opensourcedesign/fonts/blob/master/gnu-freefont_freesans/FreeSans.otf or do the rawgit CDN?
2. P_4_2_2_01, yes reduce it ... eg. try uploading to vimeo and download then the compressed version ... and/or simply remove the .ogg video (also in code) to free up some space
3. Sorry no time for testing :( This week and next week are the examen and exhibition weeks at HfG = the two most intense weeks in the semester.

**Comment by joeyklee** [comment]
1. Ok so there's progress! All fonts are now rawgit linked from our account. Font based sketches should be working. Still need to test. 

<img width="1528" alt="screen shot 2018-02-02 at 09 10 47" src="https://user-images.githubusercontent.com/3622055/35737435-6dfdac70-07f9-11e8-8f71-756870322b14.png">


2. Will look into the video/vimeo issue/webhosting issue. I wonder if we can rawgit that too.  

3. All good. I will test as many as possible and then sync up with Cassie next week to upload stuff to the web.

**Comment by joeyklee** [comment]
## List of Checked Sketches in p5 Editor (local)

- [ ] P_1_0_01
- [ ] P_1_1_1_01
- [ ] P_1_1_2_01
- [ ] P_1_2_1_01
- [ ] P_1_2_2_01
- [ ] P_1_2_3_01
- [ ] P_1_2_3_02
- [ ] P_1_2_3_03
- [ ] P_1_2_3_04
- [ ] P_1_2_3_05
- [ ] P_2_0_01
- [ ] P_2_0_02
- [ ] P_2_0_03
- [ ] P_2_1_1_01
- [ ] P_2_1_1_02
- [ ] P_2_1_1_03
- [ ] P_2_1_1_04
- [ ] P_2_1_2_01
- [ ] P_2_1_2_02
- [ ] P_2_1_2_03
- [ ] P_2_1_2_04
- [ ] P_2_1_3_01
- [ ] P_2_1_3_02
- [ ] P_2_1_3_03
- [ ] P_2_1_3_04
- [ ] P_2_1_3_05
- [ ] P_2_1_4_01
- [ ] P_2_1_4_02
- [ ] P_2_1_4_03
- [ ] P_2_1_4_04
- [ ] P_2_1_5_01
- [ ] P_2_1_5_02
- [ ] P_2_1_5_03
- [ ] P_2_1_5_04
- [ ] P_2_2_1_01
- [ ] P_2_2_1_02
- [ ] P_2_2_2_01
- [ ] P_2_2_2_02
- [ ] P_2_2_3_01
- [ ] P_2_2_3_02
- [ ] P_2_2_4_01
- [ ] P_2_2_4_02
- [ ] P_2_2_4_02_class_version
- [ ] P_2_2_5_01
- [ ] P_2_2_5_02
- [ ] P_2_2_6_01
- [ ] P_2_2_6_01_class_version
- [ ] P_2_2_6_02
- [ ] P_2_2_6_03
- [ ] P_2_2_6_04
- [ ] P_2_2_6_05
- [ ] P_2_3_1_01
- [ ] P_2_3_1_02
- [ ] P_2_3_2_01
- [ ] P_2_3_3_01
- [ ] P_2_3_4_01
- [ ] P_2_3_5_01_TABLET
- [ ] P_2_3_6_01
- [ ] P_2_3_6_02
- [ ] P_2_3_7_01
- [ ] P_2_3_7_02_TABLET
- [ ] P_3_0_01
- [ ] P_3_1_1_01
- [ ] P_3_1_2_01
- [ ] P_3_1_2_02
- [ ] P_3_1_3_01
- [ ] P_3_1_3_02
- [ ] P_3_1_3_03
- [ ] P_3_1_3_04
- [ ] P_3_1_3_05
- [ ] P_3_1_4_01
- [ ] P_3_1_4_02
- [ ] P_3_2_1_01
- [ ] P_3_2_1_02
- [ ] P_3_2_2_01
- [ ] P_3_2_3_01
- [ ] P_3_2_4_01
- [ ] P_3_2_5_01
- [ ] P_3_2_5_02
- [ ] P_3_2_5_03
- [ ] P_4_0_01
- [ ] P_4_1_1_01
- [ ] P_4_1_2_01
- [ ] P_4_1_2_02
- [ ] P_4_2_1_01
- [ ] P_4_2_1_02
- [ ] P_4_2_2_01
- [ ] P_4_2_2_02
- [ ] P_4_2_3_01
- [ ] P_4_2_3_02
- [ ] P_4_2_3_03
- [ ] P_4_2_3_04
- [ ] P_4_3_1_01
- [ ] P_4_3_1_02
- [ ] P_4_3_2_01
- [ ] P_4_3_3_01
- [ ] P_4_3_3_02
- [ ] P_4_3_4_01
- [ ] P_4_3_4_01_emoji_icon_analyser
- [ ] P_4_3_4_02
- [ ] M_1_1_01
- [ ] M_1_2_01
- [ ] M_1_3_01
- [ ] M_1_3_02
- [ ] M_1_3_03
- [ ] M_1_4_01
- [ ] M_1_5_01
- [ ] M_1_5_02
- [ ] M_1_5_03
- [ ] M_1_5_04
- [ ] M_2_1_01
- [ ] M_2_2_01
- [ ] M_2_3_01
- [ ] M_2_3_02
- [ ] M_2_5_01
- [ ] M_2_5_02
- [ ] M_5_1_01
- [ ] M_6_1_01
- [ ] M_6_1_02
- [ ] M_6_1_03
- [ ] M_6_2_01
- [ ] M_6_2_02

**Comment by joeyklee** [comment]
## Updates:

- So the above sketches that are checked off are working! 
- SVG support is working through external linking. RawGit is taking care, but the only thing is with project ` P_2_3_6_01 ==> svg issues` & `P_2_3_6_02 ==> svg issues` loading all those svg's in the beginning is proving not to work. Maybe we need promises or something? 
- weird Dom issues for ` P_2_1_4_01` and `P_2_1_4_02` ==> not sure yet what's up there. will investigate.
- P_4_3_4_01 `Tweemoji` library is gigantic. not sure what the best way to do that one is.
- Video camera sketches seem not to work. still tbd 
- can't test the tablet ones.

**Comment by b-g** [comment]
@joeyklee Super great to read all the progress! 🙏

* If things are to painful and just don't make sense for the p5-online-editor e.g. like handling 1000 png files of Tweemoji I wold vote to simply exclude them.
* Please add the `// noprotect` if needed
* Will have a look on the tablet ones, once I have more time e.g. after HfG exhibition next weekend

**Comment by joeyklee** [comment]
@b-g:

+ Re tweemoji: I'd like to change the sketch code as little as possible/not at all compared to what is in the repo. The issue with the tweemoji files is that even if we were able to reference them from the rawgit cdn given they are already on github is the downloading issue in the sketch. I think for now it is better to drop the sketches with massive data dependencies for the p5.js editor.
+ Re noprotect: seems //noprotect is buggy. Still tbd: https://github.com/processing/p5.js-web-editor/issues/455

**Comment by b-g** [comment]
@joeyklee 
Thanks for the update! Yes let's be pragmatic!

One last idea for the bigger data dependent sketches could also be: 
Instead of a CDN service we could simply publish a data repo e.g. the master branch https://github.com/generative-design/data with github pages. That way we could directly link to all the assets without "polluting" the Code-Package-p5.js repository.

**Comment by joeyklee** [comment]
@b-g so here's just one quirk of the p5.editor:

1. Notice that there's svg's in the "data" folder:

<img width="1476" alt="screen shot 2018-02-07 at 10 19 18" src="https://user-images.githubusercontent.com/3622055/35924232-7d43ee38-0bf0-11e8-9659-6058d10d4f22.png">

2. But those svgs are not flat files, rather when they are stored to mongo, they are just references to the cdn from which they are served. Same deal for images I believe and other assets to keep the mongodb storage down. So while there appears to be something in the "data" folder, it is an external link. 

<img width="1476" alt="screen shot 2018-02-07 at 10 19 21" src="https://user-images.githubusercontent.com/3622055/35924275-9a5b9e80-0bf0-11e8-93f7-4862fc8fbc4c.png">

**Comment by joeyklee** [comment]
Offtopics ^^: so in principle, these two sketches should work in the p5 editor but we'd need to write out the `loadImage()` function for each module rather than loop through (due to the request/response issue mentioned above) :

*  P_2_3_6_01 ==> svg issues
* P_2_3_6_02 ==> svg issues

**Comment by b-g** [comment]
Ok ... just refactor/change it, just please make sure not "touch" code which is printed in the book.

**Comment by joeyklee** [comment]
@b-g Just to clarify:

- it is ok to change the part of the code from a sketch that is in the book, but just not printed in the explanation section, correct?

meaning:

1. take for example, sketch `P_2_3_6_01`.
2. It is a sketch that is featured in the book
3. BUT the SVG loading via `loadImage()` is not featured in the book, just everything around it. 

In that case, is it ok to change the loadImage() mechanism? and if so, should I change it in `pre-release` or just in `gg4editor`?

thanks!

**Comment by b-g** [comment]
@joeyklee 
> it is ok to change the part of the code from a sketch that is in the book, but just not printed in the explanation section, correct?

Yes. 

Changing any printed code is really painful, but the parts outside of the "viewport" of the pages of the book are fine.

**Comment by b-g** [comment]
I would vote do such sketch code changes in the `pre-release` branch only.

**Comment by joeyklee** [comment]
## outstanding issues
- [ ] P_4_2_1_01 ==> needs _footage folder in the heirarchy ==> cdn rawgit them
- [ ] P_4_2_1_02 ==> needs _footage folder in the heirarchy ==> cdn rawgit them
- [ ] P_4_2_3_02 ==> vvt file & video // this is the supercut
- [ ] P_4_2_3_03 ==> vvt file & video // this is the supercut
- [ ] P_4_2_3_04 ==> vvt file & video // this is the supercut
- [ ] P_4_2_3_01 ==> vvt file & video // this is the supercut
- [ ] P_4_3_4_02  ==> twemoji lib
- [ ] P_4_3_4_01_emoji_icon_analyser => null // twemoji lib
- [ ] P_4_3_4_01  => png //twemoji lib
- [ ] P_2_3_5_01_TABLET ==> not sure. no tablet available
- [ ] P_2_3_7_02_TABLET ==> no tablet to test
- [ ] P_2_3_6_02 ==> svg issues // waaay too many svgs to load individually... or?

**Comment by joeyklee** [comment]
@Niels-NTG - The home stretch now! To coordinate with the sketch index page:

## Sketch paths to p5 web editor:

To link the sketches from the p5.js web editor to index page, the links will look like this:

`https://alpha.editor.p5js.org/generative-design/sketches/P_1_0_01` ==> `https://editor.p5js.org/generative-design/sketches/P_1_0_01`

Note: there is no: `01_P/...` or `02_M` appended in front of the sketches.


## Exclude sketches

After discussion with @b-g, the decision is to leave out the following sketches:

```
P_4_2_1_01 ==> needs _footage folder in the heirarchy ==> cdn rawgit them
P_4_2_1_02 ==> needs _footage folder in the heirarchy ==> cdn rawgit them
P_4_2_3_02 ==> vvt file & video // this is the supercut
P_4_2_3_03 ==> vvt file & video // this is the supercut
P_4_2_3_04 ==> vvt file & video // this is the supercut
P_4_2_3_01 ==> vvt file & video // this is the supercut
P_4_3_4_02 ==> twemoji lib
P_4_3_4_01_emoji_icon_analyser => null // twemoji lib
P_4_3_4_01 => png //twemoji lib
P_2_3_5_01_TABLET ==> not sure. no tablet available
P_2_3_7_02_TABLET ==> no tablet to test
P_2_3_6_02 ==> svg issues // waaay too many svgs to load individually... or?
```

Maybe a simple conditional looping through this list could be a way to quickly exclude those sketches:

```
const ignoreSketches = ['P_4_2_1_01', 'P_4_2_1_02', 'P_4_2_3_02', 'P_4_2_3_03', 'P_4_2_3_04', 'P_4_2_3_01', 'P_4_3_4_02', 'P_4_3_4_01_emoji_icon_analyser', 'P_4_3_4_01', 'P_2_3_5_01_TABLET', 'P_2_3_7_02_TABLET', 'P_2_3_6_02']
```


Let me know if this make sense and if you need any clarification. Happy to hop on a call if necessary! 

Thanks!

**Comment by Niels-NTG** [comment]
@joeyklee For the website I kept it really stupid and simple and just commented out the sketches you listed until further notice. https://github.com/generative-design/generative-design-website-2/commit/73955ce5f4d7abca3328287aca94d73f0fc97e48

**Comment by b-g** [comment]
@joeyklee Can we close this issue and remove the related branch?

**Comment by joeyklee** [comment]
@Niels-NTG - super thanks for doing that. Also apologies for the late reply. 

@b-g: I will make  pull-request to the p5-web-editor to change the branch to `master`. Right now the chron job will be taking the sketches from the `gg4editor` branch. Do we want to keep a separate branch for the p5 editor sketches?

**Comment by b-g** [comment]
@joeyklee I think it would be better to have just a single branch ... you know minimum complexity ... we will have to maintain it for years :)

**Comment by joeyklee** [comment]
@b-g Alles Klar! I will take care and rm the gg4editor branch. Thanks!

**Comment by joeyklee** [comment]
alrighty should be closed now with https://github.com/generative-design/Code-Package-p5.js/commit/79e533f02dbc95e3eacbfa179b40420869e2b981
