### ISSUE TITLE
Readme: improve local webserver and setup instructions 

### ISSUE THREAD

**Issue by b-g** [generative-design/Code-Package-p5.js#168]
@joeyklee 

Could you go once more over the readme?

At the moment it reads like you have to install node to run everything, but running index.html in any kind of local webserver would be enough. Could you make the node thing more optional and point out that any local webserver will do?

**Comment by joeyklee** [comment]
@b-g - Ah good point. Yes, I will add that in. Should the changes be to `pre-release` branch or otherwise?

**Comment by joeyklee** [comment]
should be addressed with https://github.com/generative-design/Code-Package-p5.js/commit/79e533f02dbc95e3eacbfa179b40420869e2b981
