### ISSUE TITLE
Maintenance + updating to more recent p5.js version

### ISSUE THREAD

**Issue by b-g** [generative-design/Code-Package-p5.js#169]
Hi @Niels-NTG @joeyklee @bohnacker, hope this github issue finds you alle well!

It think it would be a good idea to do some maintenance for the new/upcoming version JP/EN of the book. There will be a new wave of attention and we should be best possible prepared for this. Hence could all of us invest a little time in this? I'm thinking of:

- [x] Update p5.js dependency to the most recent stable p5.js version
- [x] @joeyklee could you reach out to your p5.js friends and ask for advice? Which recent version is the best bet for long term support?
- [x] Create a dev branch for this
- [x] Check and fix every sketch, with local webserver
- [x] Check and fix every sketch, with the http://alpha.editor.p5js.org/generative-design/
...

Happy to split the work ... :)

PS. @Niels-NTG kind of related ... is there still the plan to have the sketches running interactively on http://www.generative-gestaltung.de/2/

**Comment by Niels-NTG** [comment]
Sketch viewer page is complete and online!

**Comment by b-g** [comment]
@Niels-NTG Mega!!

Feedback:
* Would find it better to not open the sketches in a new tab
* If we agree on a singe tab ... then I would add a "back arrow" in the header
* Layout sketch header: as the sketch is running ideally fullscreen ... it would be nice to align far left and right. Doesn't makes sense imo to reflect the column of the main site in the sketch player view.

![2018-08-09 at 09 07](https://user-images.githubusercontent.com/480224/43883607-f133f6a0-9bb3-11e8-9ff4-59acba1bdea8.png)

**Comment by joeyklee** [comment]
Hey all! Apologies for the slow reply. Getting caught up on web stuff. 
> @joeyklee could you reach out to your p5.js friends and ask for advice? Which recent version is the best bet for long term support?
+ I can ping Lauren, but quite likely the latest version would be the best way to go, or?

> Check and fix every sketch, with the http://alpha.editor.p5js.org/generative-design/
+ Yep, there's a bunch of issues that I'll need to go through systematically and update. 

Thanks for your patience! 

@Niels-NTG - bravo on the sketches working directly on the site! 🤙

**Comment by b-g** [comment]
Hi @joeyklee, great! Yes you are right, no need to ping Lauren as we should simply go with the latest one which is currently running in the p5 online editor. Best, B PS. Congrats on the position!

**Comment by joeyklee** [comment]
@b-g - Cool! Word on the street is that there's also the launch of the v1 of the p5 editor soon ;) 
+ Thanks! I will ping you via email - I could use some teaching tips!

**Comment by joeyklee** [comment]
Hi All,
Apologies for the super late action on my side. 

I'm adding/updating changes to:

https://github.com/generative-design/Code-Package-p5.js/tree/dev-updates 

I'm starting to dive into the updates. A few notes:

## firefox blocks CORS for gg-dependency-bundle.js in the p5 editor:

* a work around is to convert all our rawgit ==>  http://raw.githack.com/ 

## Uploading files to the p5 editor has changed

* it now seems that the p5 editor has storage for files, so it seems possible that we can get around some of those issues we were running into for the sketches that involve .svg and font files. 
* quite likely we'd have to update the script the uploads data to the p5 editor server.

**Comment by joeyklee** [comment]
## Checking Sketches List

I will go down this list 1 by 1 and check if the sketches are working in the **current version of the p5 web editor** locally before I make a pull request to the p5.js-web-editor on my gg4editor branch (https://github.com/joeyklee/p5.js-web-editor/tree/gg4editor) regarding any updates and changes. 

## P
- [X] P_1_0_01
- [X] P_1_1_1_01
- [ ] P_1_1_2_01
- [ ] P_1_2_1_01
- [ ] P_1_2_2_01
- [ ] P_1_2_3_01
- [ ] P_1_2_3_02
- [ ] P_1_2_3_03
- [ ] P_1_2_3_04
- [ ] P_1_2_3_05
- [ ] P_2_0_01
- [ ] P_2_0_02
- [ ] P_2_0_03
- [ ] P_2_1_1_01
- [ ] P_2_1_1_02
- [ ] P_2_1_1_03
- [ ] P_2_1_1_04
- [ ] P_2_1_2_01
- [ ] P_2_1_2_02
- [ ] P_2_1_2_03
- [ ] P_2_1_2_04
- [ ] P_2_1_3_01
- [ ] P_2_1_3_02
- [ ] P_2_1_3_03
- [ ] P_2_1_3_04
- [ ] P_2_1_3_05
- [ ] P_2_1_4_01
- [ ] P_2_1_4_02
- [ ] P_2_1_4_03
- [ ] P_2_1_4_04
- [ ] P_2_1_5_01
- [ ] P_2_1_5_02
- [ ] P_2_1_5_03
- [ ] P_2_1_5_04
- [ ] P_2_2_1_01
- [ ] P_2_2_1_02
- [ ] P_2_2_2_01
- [ ] P_2_2_2_02
- [ ] P_2_2_3_01
- [ ] P_2_2_3_02
- [ ] P_2_2_4_01
- [ ] P_2_2_4_02
- [ ] P_2_2_4_02_class_version
- [ ] P_2_2_5_01
- [ ] P_2_2_5_02
- [ ] P_2_2_6_01
- [ ] P_2_2_6_01_class_version
- [ ] P_2_2_6_02
- [ ] P_2_2_6_03
- [ ] P_2_2_6_04
- [ ] P_2_2_6_05
- [ ] P_2_3_1_01
- [ ] P_2_3_1_02
- [ ] P_2_3_2_01
- [ ] P_2_3_3_01
- [ ] P_2_3_3_01_TABLET
- [ ] P_2_3_4_01
- [ ] P_2_3_5_01_TABLET
- [ ] P_2_3_6_01
- [ ] P_2_3_6_02
- [ ] P_2_3_7_01
- [ ] P_2_3_7_02_TABLET
- [ ] P_3_0_01
- [ ] P_3_1_1_01
- [ ] P_3_1_2_01
- [ ] P_3_1_2_02
- [ ] P_3_1_3_01
- [ ] P_3_1_3_02
- [ ] P_3_1_3_03
- [ ] P_3_1_3_04
- [ ] P_3_1_3_05
- [ ] P_3_1_4_01
- [ ] P_3_1_4_02
- [ ] P_3_2_1_01
- [ ] P_3_2_1_02
- [ ] P_3_2_2_01
- [ ] P_3_2_3_01
- [ ] P_3_2_4_01
- [ ] P_3_2_5_01
- [ ] P_3_2_5_02
- [ ] P_3_2_5_03
- [ ] P_4_0_01
- [ ] P_4_1_1_01
- [ ] P_4_1_2_01
- [ ] P_4_1_2_02
- [ ] P_4_2_1_01
- [ ] P_4_2_1_02
- [ ] P_4_2_2_01
- [ ] P_4_2_2_02
- [ ] P_4_2_3_01
- [ ] P_4_2_3_02
- [ ] P_4_2_3_03
- [ ] P_4_2_3_04
- [ ] P_4_3_1_01
- [ ] P_4_3_1_02
- [ ] P_4_3_2_01
- [ ] P_4_3_3_01
- [ ] P_4_3_3_02
- [ ] P_4_3_4_01
- [ ] P_4_3_4_01_emoji_icon_analyser
- [ ] P_4_3_4_02

## M

- [ ] M_1_1_01
- [ ] M_1_2_01
- [ ] M_1_3_01
- [ ] M_1_3_02
- [ ] M_1_3_03
- [ ] M_1_4_01
- [ ] M_1_5_01
- [ ] M_1_5_02
- [ ] M_1_5_03
- [ ] M_1_5_04
- [ ] M_2_1_01
- [ ] M_2_2_01
- [ ] M_2_3_01
- [ ] M_2_3_02
- [ ] M_2_5_01
- [ ] M_2_5_02
- [ ] M_5_1_01
- [ ] M_6_1_01
- [ ] M_6_1_02
- [ ] M_6_1_03
- [ ] M_6_2_01
- [ ] M_6_2_02

**Comment by b-g** [comment]
Hi @Niels-NTG, @joeyklee, Many thanks!! I just merged PR #170 ... I think we can close then this issue, or? 

Q:
* Can I create a v1.1.0 release
* Add "maintenance release; upgrading to p5.js 0.7.2" to the changelog?
* Joey: Could you deploy the sketches to the online editor?
* Niels: Could you deploy the sketches to the website?

**Comment by Niels-NTG** [comment]
@b-g Deploying the sketches to the website is already on my list. I will do it later today. And yes, go ahead with creating the new release tag.

**Comment by b-g** [comment]
Done. Tagged and released v1.1.0. https://github.com/generative-design/Code-Package-p5.js/releases
