### ISSUE TITLE
gd not defined in P_1_2_2_01

### ISSUE THREAD

**Issue by IDdesigner** [generative-design/Code-Package-p5.js#171]
Console says that 'gd' is not defined. First mention of 'gd' is at line 69 in the P5 editor.

**Comment by Niels-NTG** [comment]
@joeyklee As far as I can see there is nothing wrong with the source code itself. Seem like the resources, including the images are misplaced somewhere on the server. Can you take a look at this?

**Comment by joeyklee** [comment]
@Niels-NTG  - this may be a p5 web editor issue for now. The images aren't being served up for some reason in this instance which is another issue. As there is a public API coming for the web editor soon, we will be more easily able to update and edit these kinds of funky issues in the future. For now, I will close this issue. Thanks!
