### ISSUE TITLE
Question about uploading to p5.js editor

### ISSUE THREAD

**Issue by haschdl** [generative-design/Code-Package-p5.js#172]
Slightly off-topic. I was wondering if in the development of this project you used some automation to publish the sketches in the p5.js editor? 

I'm porting a book project with ~50 Processing sketches to p5js, and it would be great to publish them in the portal too. It is all in Github.  How did you do, was it all manual? :)

**Comment by haschdl** [comment]
Thanks @Niels-NTG . I'm glad to remove the issue if @joeyklee  and team prefer to discuss in another channel.

**Comment by Niels-NTG** [comment]
It was @joeyklee who was responsible for uploading them to the p5.js editor servers. Me personally, I have no experience with that aspect of our project. But you can ask me any question about the code itself. 😄

**Comment by joeyklee** [comment]
@Niels-NTG - Hi! It has been ages. I'd love to hear what you're up to!

@haschdl - Hi! Thanks for reaching out. So at the moment, we are connected to @catarak, the creator of the p5 web editor and she allowed us to create a custom batch upload script. This might be a special circumstance though. 

However there is hope! I know the p5 web editor team is currently working on developing a client facing API to implement this kind of task (see: https://github.com/processing/p5.js-web-editor/issues/1095). I think this is a high priority so maybe keep an eye on those developments for now?

**Comment by catarak** [comment]
@haschdl joey is indeed right that we're working on a public API right now, so that you could write your own script! i'd love to have you as an early tester of this feature. i think it will be ready within the next month or so!

**Comment by joeyklee** [comment]
Thanks for your input @catarak ! Suuuper excited for this feature.

**Comment by haschdl** [comment]
> @haschdl joey is indeed right that we're working on a public API right now, so that you could write your own script! i'd love to have you as an early tester of this feature. i think it will be ready within the next month or so!

Thank you everyone for the input! @catarak I'd be more than happy to test the feature. How could I reach out to you?

**Comment by haschdl** [comment]
Closing. The functionality will be available as an API from p5.js editor.
