### ISSUE TITLE
Blocked by CORS

### ISSUE THREAD

**Issue by everythingability** [generative-design/Code-Package-p5.js#173]
Sure this is fixable

**Comment by Niels-NTG** [comment]
What exactly is being blocked by CORS restrictions?

**Comment by everythingability** [comment]
Oh sorry, the example in the p5js example (the last two on your site) doesn't work. It was loading something from http rather than https (or something).

**Comment by Niels-NTG** [comment]
@everythingability After some delay (sorry about that) I've uploaded updated code for all the examples to our website, including M_6_2_01 and M_6_2_02. They should now work as intended. Let us know if any problems remain.
