### ISSUE TITLE
Bug in P_1_2_1_01

### ISSUE THREAD

**Issue by whatsnewsisyphus** [generative-design/Code-Package-p5.js#175]
https://github.com/generative-design/Code-Package-p5.js/blob/master/01_P/P_1_2_1_01/sketch.js
Line 53, if you move the mouse beyond the canvas, it will fall out of the map range and make tileCountY undefined. It either needs a fallback, or a constraint on mouseY   tileCountY = int(map(constrain(mouseY,0,height), 0, height, 2, 10));

**Comment by Niels-NTG** [comment]
This should be resolved now. I ended up implementing your proposed solution. Thanks!

**Comment by b-g** [comment]
@Niels-NTG Many thanks for taking care of this and the new release! Cheers!
