### ISSUE TITLE
404 link on generative-gestaltung.de

### ISSUE THREAD

**Issue by SableRaf** [generative-design/Code-Package-p5.js#183]
The link to Princeton Architectural Press is 404:

https://papress.com/products/generative-design-revised-and-updated-edition-visualize-program-and-create-with-javascript-in-p5js

I couldn't find the book on their website using the search function either :/

**Comment by bohnacker** [comment]
Hi @SableRaf,
you're right. It seems that they have taken the book out of their store. Probably because its sold out and they are not continuing to print it. :-(

**Comment by Niels-NTG** [comment]
I will update the website soon.

**Comment by Niels-NTG** [comment]
Website has been [updated](https://github.com/generative-design/generative-design-website-2/commit/2509650e370de570d4e7aebbae1f2297cbcbaae3). Links to the now non-existent Princeton Architectural Press store have been removed.

**Comment by b-g** [comment]
Thanks! Just sent an email to our publishing house asking for the availability. We let you know if there is any news.
