### ISSUE TITLE
Unable to launch

### ISSUE THREAD

**Issue by mroberts1** [generative-design/Code-Package-p5.js#184]
I'm unable to launch the package from the directory with "npm start". 

I'm running node v.20.0.0, npm v.9.6.5, on MacOS 12.6.5 (Monterey).

I get this error:

```
> Generative-Design-Code-Package-p5-js@1.3.4 watch /Users/dokoissho/GitHub/gg/Code-Package-p5.js-1.3.4
> budo --host localhost --dir . --open --live --watch-glob '**/*.{html,css,js}'

ERROR getaddrinfo ENOTFOUND localhost

npm ERR! Darwin 21.6.0
npm ERR! argv "/usr/local/Cellar/node/20.0.0/bin/node" "/Users/dokoissho/node_modules/.bin/npm" "run" "watch"
npm ERR! node v20.0.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! Generative-Design-Code-Package-p5-js@1.3.4 watch: `budo --host localhost --dir . --open --live --watch-glob '**/*.{html,css,js}'`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Generative-Design-Code-Package-p5-js@1.3.4 watch script 'budo --host localhost --dir . --open --live --watch-glob '**/*.{html,css,js}''.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Generative-Design-Code-Package-p5-js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     budo --host localhost --dir . --open --live --watch-glob '**/*.{html,css,js}'
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Generative-Design-Code-Package-p5-js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Generative-Design-Code-Package-p5-js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dokoissho/GitHub/gg/Code-Package-p5.js-1.3.4/npm-debug.log
```

**Comment by Niels-NTG** [comment]
In an attempt to reproduce this issue I've reinstalled all npm packages and ran `npm run watch` under Node v20.0.0 with npm v9.6.4 and again with npm v9.6.5, also on MacOS 12.5.6. It works just fine on my end.

From looking at your error log there's seems something off about the installation of Node on your machine where it uses npm v.3.10.10 instead of a more recent version that would fit with Node v20. I suspect this could be an issue with [nvm](https://github.com/nvm-sh/nvm) (if you use that). Otherwise I recommend reinstalling Node. More specifically I would recommend using the [Homebrew](https://brew.sh) package manager for this, but that's definitely not a requirement.

**Comment by mroberts1** [comment]
I have tried everything - completely reinstalled node (20.0.0) using Homebrew, installed latest version of npm (9.6.6.) using nvm, but every time I run npm start it tries to run npm 3.10.10 and fails with the same error message as before.

**Comment by Niels-NTG** [comment]
What happens if you run the `npm run watch` command directly (`npx budo --host localhost --dir . --open --live --watch-glob '**/*.{html,css,js}'`). Does it still use this old npm version?

**Comment by Niels-NTG** [comment]
What result do you get if you run the command `whereis npm`? I would except this to return `npm: /usr/local/bin/npm /usr/local/share/man/man1/npm.1`. If the path differs, you can look through the `.zshrc` or `.bashrc` files in your home folder (`~`) to see if it includes any alias or export references to this left-over old npm version. If you find these you can remove theses lines or disable them by putting a `#` in front of it.

**Comment by mroberts1** [comment]
Okay I think I cracked it - it seems that the problem was some outdated server addresses in my /etc/hosts file - I deleted them and added 127.0.0.1 localhost and npm start opened index.html without a problem. Sorry to bother you but thanks for your help!

**Comment by Niels-NTG** [comment]
Great to hear! Happy to help.

**Comment by mroberts1** [comment]
> Great to hear! Happy to help.

Many thanks again - I had a bunch of old versions of Node so reinstalling properly with Homebrew was good advice! The book and examples are really inspiring by the way! I'm pretty new to generative art but am going down the p5.js rabbit hole... :)
