### ISSUE TITLE
M_2_1_01: Dot not on circle

### ISSUE THREAD

**Issue by FEversberg** [generative-design/Code-Package-p5.js#187]
In line 81 seems to be a problem with the operator precedence. In `x *= 100 - 125` the precedence of substraction is higher than of the assignement. So x ist constantly multiplied by -25.
Replacing it with `x = x * 100 - 125` will bring the point onto the circle.

**Comment by Niels-NTG** [comment]
Thanks you for reporting this mistake. I've fixed it in the latest release.
