### ISSUE TITLE
Add 'use strict'; to top of every script

### ISSUE THREAD

**Issue by Niels-NTG** [generative-design/Code-Package-p5.js#40]
It might be a good idea to add [`'use strict';`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode) to the top of every script. This get rid of many "silent" errors that can occur whilst running JS and promotes writing better code.

**Comment by b-g** [comment]
👍Yes please + Will do! Still busy with the new baby ... give me a bit more time. Best, B

**Comment by Niels-NTG** [comment]
I will save you some time by doing the work for you later today. Wish you the best with your new human. ;)
