### ISSUE TITLE
P_1_2_2_01, missing GenerativeDesign.sortColors()

### ISSUE THREAD

**Issue by b-g** [generative-design/Code-Package-p5.js#7]
Missing:
- if (key == 'c' || key == 'C') GenerativeDesign.saveASE()
- GenerativeDesign.sortColors()
  if (key == '5') sortMode = GenerativeDesign.HUE;
  if (key == '6') sortMode = GenerativeDesign.SATURATION;
  if (key == '7') sortMode = GenerativeDesign.BRIGHTNESS;
  if (key == '8') sortMode = GenerativeDesign.GRAYSCALE;

Task:
Implment sortColor() in generativedesign.js. Has to be most likely be implemented with webworkers: http://www.html5rocks.com/en/tutorials/workers/basics/

**Comment by bohnacker** [comment]
I've put the functions into the library, but chroma.js is not included. Has to be done at some point.
