### ISSUE TITLE
P_3_1_4_01 not feasible to completely rewrite in JS

### ISSUE THREAD

**Issue by Niels-NTG** [generative-design/Code-Package-p5.js#76]
Was [attempting](https://github.com/Niels-NTG/Code-Package-p5.js/blob/d40b637ecca264034abe1ae6f5c0431898d3cf84/01_P/P_3_1_4_01/sketch.js) to port `P_3_1_4_01.pde` and its external classes. Trying to replicate the workings of [Ben Fry's TreeMap library](http://benfry.com/writing/treemap/) proves to be quite difficult. Too many classes. I don't think it's feasible to create a sketch that behaves exactly the same as the Java version. We might have to consider replacing this sketch with one that is less complicated, or at least less awkward to write in JavaScript.

**Comment by b-g** [comment]
Thanks for trying!! I see + makes sense! What about using d3 treemap capabilities? There is d3 + p5 cookbook http://sciutoalex.github.io/p5-D3-cookbook/ which show how to make both libs works together e.g. this Voronoi examples is a good start http://sciutoalex.github.io/p5-D3-cookbook/recipes-beginner/voronoi/

**Comment by bohnacker** [comment]
I had a short look at the option of using d3 for doing this but decided, that it will bring in to many new concepts and syntax. So I wrote our own treemap class. 
@b-g We should decide, if we'll put it in the gd-library or leave it in the sketch.
